// seed/restaurants.js

const restaurant = [
  {
    name: "Spice Hut",
    address: "MG Road, Bhilai",
    cuisine: ["Indian", "Tandoori"],
    totalTables: 15,
    maxPartySize: 8,
    restaurantId: "spicehut001",
    email: "spicehut@demo.com",
    restaurantPassword: "spice123", // Will be hashed before saving
    priceRange: "$$",
    rating: 4.3,
    description: "A vibrant Indian restaurant known for its rich spices and traditional flavors.",
    openingHours: "10:00 AM - 11:00 PM",
    phone: "+91 9876543210",
    website: "https://spicehut.com",
    mainImage: "/images/spicehut-main.jpg",
    galleryImages: [
      "/images/spicehut1.jpg",
      "/images/spicehut2.jpg",
      "/images/spicehut3.jpg",
    ],
  },
  {
    name: "The Green Bistro",
    address: "Sector 6, Durg",
    cuisine: ["Continental", "Vegan"],
    totalTables: 12,
    maxPartySize: 6,
    restaurantId: "greenbistro001",
    email: "greenbistro@demo.com",
    restaurantPassword: "green123",
    priceRange: "$$",
    rating: 4.7,
    description: "Eco-friendly vegan bistro offering healthy and flavorful meals.",
    openingHours: "8:00 AM - 10:00 PM",
    phone: "+91 9898989898",
    website: "https://greenbistro.com",
    mainImage: "/images/greenbistro-main.jpg",
    galleryImages: [
      "/images/greenbistro1.jpg",
      "/images/greenbistro2.jpg",
    ],
  },
  {
    name: "The Noodle Spot",
    address: "G.E. Road, Bhilai",
    cuisine: ["Asian", "Chinese", "Thai"],
    totalTables: 20,
    maxPartySize: 4,
    restaurantId: "noodlespot001",
    email: "noodlespot@demo.com",
    restaurantPassword: "noodle123",
    priceRange: "$",
    rating: 4.1,
    description: "Serving delicious noodles and authentic Asian dishes with a modern twist.",
    openingHours: "11:00 AM - 10:00 PM",
    phone: "+91 9123456789",
    website: "https://thenoodlespot.com",
    mainImage: "/images/noodlespot-main.jpg",
    galleryImages: [
      "/images/noodlespot1.jpg",
      "/images/noodlespot2.jpg",
      "/images/noodlespot3.jpg",
    ],
  },
  {
    name: "Cafe Libro",
    address: "Nehru Nagar, Durg",
    cuisine: ["Coffee", "Italian", "Desserts"],
    totalTables: 8,
    maxPartySize: 3,
    restaurantId: "cafelibro001",
    email: "cafelibro@demo.com",
    restaurantPassword: "libro123",
    priceRange: "$",
    rating: 4.5,
    description: "A cozy cafe where books meet freshly brewed coffee and comfort food.",
    openingHours: "9:00 AM - 9:00 PM",
    phone: "+91 9876501234",
    website: "https://cafelibro.com",
    mainImage: "/images/cafelibro-main.jpg",
    galleryImages: [
      "/images/cafelibro1.jpg",
      "/images/cafelibro2.jpg",
    ],
  },
  {
    name: "Global Grills",
    address: "Housing Board Colony, Bhilai",
    cuisine: ["BBQ", "American", "Steak"],
    totalTables: 18,
    maxPartySize: 12,
    restaurantId: "globalgrills001",
    email: "globalgrills@demo.com",
    restaurantPassword: "grill123",
    priceRange: "$$$",
    rating: 4.8,
    description: "Premium BBQ and steakhouse offering an international grilling experience.",
    openingHours: "12:00 PM - 12:00 AM",
    phone: "+91 9999999999",
    website: "https://globalgrills.com",
    mainImage: "/images/globalgrills-main.jpg",
    galleryImages: [
      "/images/globalgrills1.jpg",
      "/images/globalgrills2.jpg",
      "/images/globalgrills3.jpg",
    ],
  },
];

module.exports = { data: restaurant };
